import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import AuthNavbar from "../components/AuthNavbar";
import AuthFooter from "../components/AuthFooter";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col text-white bg-zinc-950">
        <div className="min-h-screen w-full relative">
          
          {/* CONTENT */}
          <AuthNavbar />
          <div className="relative z-10">{children}</div>
          <AuthFooter />
          <Toaster
            position="top-right"
            closeButton
            toastOptions={{
              className:
                "bg-zinc-900 border border-zinc-800 text-zinc-200 shadow-lg",
            }}
          />
        </div>
      </body>
    </html>
  );
}
