import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import AppInit from "../components/AppInit";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col text-white">
        <div className="min-h-screen w-full relative">
          {/*  Gradient Background (LOWEST LAYER) */}
          <div
            className="fixed inset-0 -z-20"
            style={{
              background:
                "radial-gradient(125% 125% at 50% 10%, #000000 40%, #0d1a36 100%)",
            }}
          />

          {/* Glow Layer (ABOVE GRADIENT) */}
          <div className="fixed inset-0 -z-10 flex justify-center items-start pt-32 pointer-events-none">
            <div className="w-150 h-75 bg-cyan-500/20 blur-[120px] rounded-full" />
          </div>

          {/* CONTENT */}
          <AppInit />
          <Navbar />
          <div className="relative z-10">{children}</div>
          <Footer />
          <Toaster
            position="top-right"
            closeButton
            toastOptions={{
              className:
                "bg-zinc-900 border border-zinc-800 text-zinc-200 shadow-lg",
            }}
          />
        </div>
      </body>
    </html>
  );
}
